#!/bin/bash -l

export LAMMPS_DIR=/home/postdoc6/lammps
export MOL_FORGE=/home/postdoc6/MolForge
export DFTD3=/home/postdoc6/dftd3-lib-0.9


# The static math libraries
SCALA_FILE=/opt/cp2k-2024.3/tools/toolchain/install/scalapack-2.2.1/lib/libscalapack.a
OPENBLAS_FILE=/lib64/libopenblaso.so.0

# Dynamically finding MolForge
MOL_FORGE_LIB=$(find ${MOL_FORGE} -name "libMolForge.a" -o -name "libMolForge.so" 2>/dev/null | head -n 1)

# Force-feeding the EXACT LAMMPS wrapper archive so the linker can't ignore it
LAMMPS_FORTRAN_LIB=${LAMMPS_DIR}/examples/COUPLE/fortran2/liblammps_fortran.a

yes | rm -f snap

# Compile natively
mpif90 -c -g -O2 -I${DFTD3}/lib -I${MOL_FORGE}/Modules -I${LAMMPS_DIR}/examples/COUPLE/fortran2 parameters.f90 def_input.f90 def_lammps.f90 def_max.f90 def_geom.f90 def_SNAP.f90 def_force_field.f90 main.f90

# Link using mpif90
# Critical Fix: $LAMMPS_FORTRAN_LIB is now explicitly called AFTER $MOL_FORGE_LIB
mpif90 *.o -L$HOME/lib_fix -lstdc++ -latomic -L${LAMMPS_DIR}/src -llammps_mpi $MOL_FORGE_LIB $LAMMPS_FORTRAN_LIB -L${DFTD3}/lib -ldftd3 $SCALA_FILE $OPENBLAS_FILE -Wl,--allow-shlib-undefined -o snap

yes | rm -f *.o
yes | rm -f *.mod
